version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - 3000:3000
