version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - 3000:3000

  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    build:
      context: ./backend/mongo
      dockerfile: dev.mongo.Dockerfile
    ports:
      - 27019:27017
    extra_hosts:
      - mongo:127.0.0.1
    logging:
      driver: none
    command: mongod --replSet rsg3

  mailcatcher:
    image: schickling/mailcatcher:latest
    restart: always
    ports:
      - 1080:1080
      - 1025:1025
