
pipeline {
  agent  { node { label 'jenkins-slave' } }

  stages {
      stage("Build project") {
          steps {
              sh "npm run build-app:dev"
          }
      }
       stage("Start project") {
          steps {
              sh "npm run docker-start:dev"
          }
      }
  }
}

